# Setup
title:        CityBook
tagline:      Create a searchable, mobile-responsive contact list<br>from a Google Spreadsheet.
base_url:      ""
paginate:     1

# About/contact
author:
  name:       Code for America
  url:        http://codeforamerica.org

# Gems
gems:
  - jekyll-paginate

#Others
markdown: redcarpet
